In [1]:
%matplotlib inline

# PyTorch是什么？
基于Python的科学计算包，服务于以下两种场景
* 作为NumPy的替代品，可以使用GPU的强大计算能力
* 提供最大的灵活性和高速的深度学习研究平台

# 开始
Tensors(张量)

Tensors与Numpy中的ndarrays类似，但是在PyTorch中Tensors可以使用GPU进行计算。

In [2]:
from __future__ import print_function
import torch

创建一个5×3矩阵，但是未初始化

In [3]:
x = torch.empty(5,3)
print(x)

tensor([[-7.2630e-28,  4.5729e-41, -7.2630e-28],
        [ 4.5729e-41,         nan,  3.0970e-41],
        [ 1.7753e+28,  4.4339e+27,  5.6719e-11],
        [ 7.3471e+28,  2.6383e+23,  2.7376e+20],
        [ 1.8040e+28,  1.8750e-19,  7.3909e+22]])


创建一个随机初始化的矩阵

In [4]:
x = torch.rand(5,3)
print(x)

tensor([[0.6957, 0.8565, 0.7844],
        [0.3198, 0.9460, 0.4244],
        [0.7566, 0.7370, 0.6519],
        [0.7324, 0.3396, 0.7447],
        [0.1074, 0.1667, 0.0326]])


创建一个0填充的矩阵，数据类型为long

In [5]:
x = torch.zeros(5,3,dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化

In [6]:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


使用现有的张量创建张量。这些方法将重用输入张量的属性，例如，dtype,除非设置新的值进行覆盖

In [7]:
x = x.new_ones(5,3,dtype=torch.double) #new_*方法来创建对象
print(x)

x = torch.randn_like(x,dtype = torch.float) #覆盖dtype!
print(x)                                    #d对象的size相同，值和类型发生变化  

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 0.2724, -2.0907, -0.6096],
        [-0.3521,  1.9110, -0.0053],
        [ 1.6634,  1.4252, -0.0778],
        [ 1.1623, -0.3941, -0.8029],
        [ 0.8197,  0.0218, -1.7554]])


获取size

In [8]:
print(x.size())

torch.Size([5, 3])


"torch.Size"返回值是tuple类型，支持tuple类型的所有操作

加法1：

In [9]:
y = torch.rand(5,3)
print(x+y)

tensor([[ 3.0160e-01, -1.1085e+00,  3.4606e-01],
        [ 4.3867e-02,  2.1488e+00,  4.5966e-01],
        [ 2.5710e+00,  1.6776e+00,  8.5985e-01],
        [ 1.8511e+00, -2.2450e-01, -1.7348e-03],
        [ 1.2764e+00,  2.9380e-01, -1.3293e+00]])


加法2

In [10]:
print(torch.add(x, y))

tensor([[ 3.0160e-01, -1.1085e+00,  3.4606e-01],
        [ 4.3867e-02,  2.1488e+00,  4.5966e-01],
        [ 2.5710e+00,  1.6776e+00,  8.5985e-01],
        [ 1.8511e+00, -2.2450e-01, -1.7348e-03],
        [ 1.2764e+00,  2.9380e-01, -1.3293e+00]])


提供输出tensor作为参数(结果被填充到result作为参数）

In [11]:
result = torch.empty(5,3)
print(result)
torch.add(x,y,out=result)
print(result)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
tensor([[ 3.0160e-01, -1.1085e+00,  3.4606e-01],
        [ 4.3867e-02,  2.1488e+00,  4.5966e-01],
        [ 2.5710e+00,  1.6776e+00,  8.5985e-01],
        [ 1.8511e+00, -2.2450e-01, -1.7348e-03],
        [ 1.2764e+00,  2.9380e-01, -1.3293e+00]])


替换（任何以“_”结尾的操作都会用结果替换原变量）

In [12]:
#add x to y
y.add_(x)
print(y)

tensor([[ 3.0160e-01, -1.1085e+00,  3.4606e-01],
        [ 4.3867e-02,  2.1488e+00,  4.5966e-01],
        [ 2.5710e+00,  1.6776e+00,  8.5985e-01],
        [ 1.8511e+00, -2.2450e-01, -1.7348e-03],
        [ 1.2764e+00,  2.9380e-01, -1.3293e+00]])


你可以使用与NumPy索引方式相同的操作来进行对张量的操作

In [13]:
print(x[:,1])

tensor([-2.0907,  1.9110,  1.4252, -0.3941,  0.0218])


torch.view():可以改变张量的维度和大小

In [14]:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) #size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你只有一个元素的张量，使用.item()来得到Python数据类型的数值

In [15]:
x =torch.randn(1)
print(x)
print(x.item())

tensor([1.0249])
1.0248878002166748


如果你想要了解更多的关于Tensor的操作，可以访问[PyTorch官方文档](https://pytorch.org/docs/torch "Tensors")

# NumPy转换
将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。  
Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。
  
将一个Torch Tensor转换为NumPy数组

In [16]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [17]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


观察numpy数组的值是如何改变的。

In [18]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


NumPy Array转化成Torch Tensor  
  
使用from_numpy自动转化

In [19]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


所有的Tensor类型默认都是基于CPU，CharTensor类型不支持到NumPy的转换。
# CUDA张量
使用.to方法可以将Tensor移动到任何设备中

In [20]:
#is_available函数判断是否有cuda可以使用
#``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")            #a CUDA 设备对象
    y = torch.ones_like(x, device=device)    #直接从GPU创建张量
    x = x.to(device)                         #直接使用``.to（"cuda"）``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu",torch.double))          #``.to``也会对变量的类型做更改

tensor([2.0249], device='cuda:0')
tensor([2.0249], dtype=torch.float64)


感谢您的浏览